### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by FatCache** [jurgenhaas/toggl-ubuntu-indicator#1]
How do I install it on Ubuntu 15.04 64bit? I extracted and CD to the extracted file. Ran py indicator but didn't work. I think I don't have py command installed.

**Comment by FatCache** [comment]
what should i installed to make it run?

**Comment by FatCache** [comment]
I just did and I get this

~/Downloads/toggl-ubuntu-indicator-master$ python indicator-applet-toggl.py 
Traceback (most recent call last):
  File "indicator-applet-toggl.py", line 5, in <module>
    import appindicator
ImportError: No module named appindicator

**Comment by FatCache** [comment]
Ok. now I have no idea to do .I have all the pre-req. ~/Downloads/toggl-ubuntu-indicator-master$ python indicator-applet-toggl.py 
Traceback (most recent call last):
  File "indicator-applet-toggl.py", line 480, in <module>
    toggl     = TogglInterface()
  File "indicator-applet-toggl.py", line 56, in **init**
    self.API_KEY         = sys.argv[1]
IndexError: list index out of range

**Comment by jurgenhaas** [comment]
This is only the fork of a script from someone else, you may be better of if you asked your question in the original project. But you may want to be warned, this project hasn't been updated for more than 4 years.
